# Generated by Django 3.0.8 on 2021-07-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('new_old', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalBodyCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text_info', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('new_old', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalBody',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('new_old', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_bodies', to='address.LocalBodyCategory')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_bodies', to='address.District')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='address.Region'),
        ),
    ]
