# Generated by Django 3.0.8 on 2021-07-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localbodycategory',
            name='new_old',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='new_old',
            field=models.BooleanField(null=True),
        ),
        migrations.RemoveField(
            model_name='district',
            name='region',
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ManyToManyField(related_name='districts', to='address.Region'),
        ),
    ]
