# Generated by Django 3.0.8 on 2021-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20210731_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localbodycategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
