# Generated by Django 3.0.8 on 2021-08-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20210731_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='new_old',
        ),
        migrations.RemoveField(
            model_name='district',
            name='region',
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_province_of', to='address.Region'),
        ),
        migrations.AddField(
            model_name='district',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_zone_of', to='address.Region'),
        ),
    ]
