# Generated by Django 3.0.8 on 2021-08-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20210803_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localbodycategory',
            old_name='text_info',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_province_of', to='address.Region'),
        ),
        migrations.AlterField(
            model_name='district',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_zone_of', to='address.Region'),
        ),
    ]
