from address.models import *

def run():
    Region(id=1001, name="Bagmati", new_old=0).save()
    Region(id=1002, name="Janakpur", new_old=0).save()
    Region(id=1003, name="Narayani", new_old=0).save()
    Region(id=1004, name="Koshi", new_old=0).save()
    Region(id=1005, name="Mechi", new_old=0).save()
    Region(id=1006, name="Sagarmatha", new_old=0).save()
    Region(id=1007, name="Mahakali", new_old=0).save()
    Region(id=1008, name="Seti", new_old=0).save()
    Region(id=1009, name="Bheri", new_old=0).save()
    Region(id=1010, name="Karnali", new_old=0).save()
    Region(id=1011, name="Rapti", new_old=0).save()
    Region(id=1012, name="Dhaulagiri", new_old=0).save()
    Region(id=1013, name="Gandaki", new_old=0).save()
    Region(id=1014, name="Lumbini", new_old=0).save()
    Region(id=1101, name="Province No. 1", new_old=1).save()
    Region(id=1102, name="Province No. 2", new_old=1).save()
    Region(id=1103, name="Bagmati", new_old=1).save()
    Region(id=1104, name="Gandaki", new_old=1).save()
    Region(id=1105, name="Lumbini", new_old=1).save()
    Region(id=1106, name="Karnali", new_old=1).save()
    Region(id=1107, name="Sudurpashchim", new_old=1).save()
