# Generated by Django 3.0.8 on 2021-08-05 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipAct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenshipType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(max_length=32)),
                ('address_old_new', models.BooleanField()),
                ('perma_old_new', models.BooleanField()),
                ('birth_ward_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)])),
                ('dob_bs', models.DateField()),
                ('father_first_name', models.CharField(max_length=32)),
                ('father_middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('father_last_name', models.CharField(max_length=32)),
                ('father_citizenship_id', models.IntegerField()),
                ('mother_first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('mother_middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('mother_last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('mother_citizenship_id', models.IntegerField()),
                ('is_married', models.BooleanField()),
                ('spouse_first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('spouse_middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('spouse_last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('spouse_citizenship_id', models.IntegerField(blank=True, null=True)),
                ('issue_date_bs', models.DateField()),
                ('birth_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='born_citizens', to='address.District')),
                ('birth_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='born_citizens', to='address.LocalBody')),
                ('birth_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='born_citizens', to='address.Region')),
                ('citizenship_act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizenships', to='documents.CitizenshipAct')),
                ('citizenship_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizenships', to='documents.CitizenshipType')),
                ('perma_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perma_citizens', to='address.District')),
                ('perma_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perma_citizens', to='address.LocalBody')),
                ('perma_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perma_citizens', to='address.Region')),
            ],
        ),
    ]
