# Generated by Django 3.2.4 on 2021-08-13 18:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0006_auto_20210803_1545'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('citizenship_no', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('photo_front', models.FileField(blank=True, null=True, upload_to='citizenship/')),
                ('photo_back', models.FileField(blank=True, null=True, upload_to='citizenship/')),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(max_length=32)),
                ('birth_new_old', models.BooleanField()),
                ('birth_ward_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)])),
                ('perma_new_old', models.BooleanField()),
                ('perma_ward_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)])),
                ('dob_bs', models.DateField()),
                ('father_first_name', models.CharField(max_length=32)),
                ('father_middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('father_last_name', models.CharField(max_length=32)),
                ('father_citizenship_id', models.IntegerField()),
                ('mother_first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('mother_middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('mother_last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('mother_citizenship_id', models.IntegerField(blank=True, null=True)),
                ('is_married', models.BooleanField()),
                ('spouse_first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('spouse_middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('spouse_last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('spouse_citizenship_id', models.IntegerField(blank=True, null=True)),
                ('face_photo', models.FileField(blank=True, null=True, upload_to='citizenship/')),
                ('issue_date_bs', models.DateField()),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citizenships', to='accounts.approval')),
                ('birth_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='born_citizens', to='address.district')),
                ('birth_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='born_citizens', to='address.localbody')),
                ('birth_local_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='born_citizens', to='address.localbodycategory')),
                ('birth_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='born_citizens', to='address.region')),
            ],
        ),
        migrations.CreateModel(
            name='CitizenshipAct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenshipType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicenseIssueCentre',
            fields=[
                ('centre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_issue_centers', to='address.district')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_issue_centers', to='address.localbody')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_issue_centers', to='address.region')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('license_category', multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A: Motorycle, Scooter, Moped'), ('B', 'B: Car, Jeep, Delivery Van'), ('K', 'K: Scooter, Moped'), ('C', 'C: Tempo, Auto Ricksaw'), ('C1', 'C1: E-Rickshaw'), ('D', 'D: Power Tiller'), ('E', 'E: Tractor'), ('F', 'F: Minibus, Minitruck'), ('G', 'G: Truck, Bus, Lorry'), ('H', 'H: Road Roller, Dozer'), ('H1', 'H1:Dozer'), ('H2', 'H2: Road Roller'), ('I', 'I: Crane, Fire Brigade, Loader'), ('I1', 'I1: Crane'), ('I2', 'I2: Fire Brigade'), ('I3', 'I3: Loader'), ('J1', 'J1: Excavator'), ('J2', 'J2: Backhoe Loader'), ('J3', 'J3: Grader'), ('J4', 'J4: Forklift'), ('J5', 'J5: Other')], max_length=32)),
                ('document_photo', models.FileField(blank=True, null=True, upload_to='license/')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='accounts.approval')),
                ('issue_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='documents.drivinglicenseissuecentre')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.PositiveIntegerField(blank=True, null=True)),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.citizenship')),
                ('driving_license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.drivinglicense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='citizenship',
            name='citizenship_act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizenships', to='documents.citizenshipact'),
        ),
        migrations.AddField(
            model_name='citizenship',
            name='citizenship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizenships', to='documents.citizenshiptype'),
        ),
        migrations.AddField(
            model_name='citizenship',
            name='perma_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perma_citizens', to='address.district'),
        ),
        migrations.AddField(
            model_name='citizenship',
            name='perma_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perma_citizens', to='address.localbody'),
        ),
        migrations.AddField(
            model_name='citizenship',
            name='perma_local_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perma_citizens', to='address.localbodycategory'),
        ),
        migrations.AddField(
            model_name='citizenship',
            name='perma_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perma_citizens', to='address.region'),
        ),
    ]
