# Generated by Django 3.0.8 on 2021-08-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenship',
            name='face_photo',
            field=models.FileField(default=None, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizenship',
            name='photo_back',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='citizenship',
            name='photo_front',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
