# Generated by Django 3.0.8 on 2021-08-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '__first__'),
        ('documents', '0002_auto_20210806_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicenseCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='citizenship',
            name='citizenship_no',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DrivingLicenseIssueCentre',
            fields=[
                ('centre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_issue_centers', to='address.District')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_issue_centers', to='address.LocalBody')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_issue_centers', to='address.Region')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('document_photo', models.FileField(blank=True, null=True, upload_to='media/')),
                ('issue_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='documents.DrivingLicenseIssueCentre')),
            ],
        ),
    ]
