# Generated by Django 3.0.8 on 2021-08-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20210806_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodGroup',
        ),
        migrations.RemoveField(
            model_name='drivinglicense',
            name='issue_centre',
        ),
        migrations.DeleteModel(
            name='DrivingLicenseCategory',
        ),
        migrations.RemoveField(
            model_name='drivinglicenseissuecentre',
            name='district',
        ),
        migrations.RemoveField(
            model_name='drivinglicenseissuecentre',
            name='local',
        ),
        migrations.RemoveField(
            model_name='drivinglicenseissuecentre',
            name='province',
        ),
        migrations.RenameField(
            model_name='citizenship',
            old_name='address_old_new',
            new_name='address_new_old',
        ),
        migrations.RenameField(
            model_name='citizenship',
            old_name='perma_old_new',
            new_name='perma_new_old',
        ),
        migrations.DeleteModel(
            name='DrivingLicense',
        ),
        migrations.DeleteModel(
            name='DrivingLicenseIssueCentre',
        ),
    ]
